from . import accr_food
from . import accr_food_group
from . import accr_food_ingredients
from . import accr_food_textures
from . import accr_diet
from . import accr_diet_plan
from . import accr_nutrition_plan
from . import accr_physical_activity
from . import accr_bca
from . import accr_bca_bmr
from . import accr_student_food_intolerance
from . import accr_student_food_preferences
from . import accr_student_nutrition_details
from . import accr_nutrition_follow_up
from . import accr_student_orientation
from . import accr_meal_type
from . import accr_meal_timing
from . import accr_meal_timetable
from . import accr_medical_contraindication
from . import accr_medical_unit_medicine
from . import accr_nutrition_student
from . import accr_nutrition_details_min
from . import accr_nutrition_details_vit
from . import accr_nutrition_notification
# from . import accr_student