from . import accr_food
from . import accr_food_group
from . import accr_food_type
from . import accr_diet
from . import accr_physical_activity
from . import accr_requirements
from . import accr_water_intake
from . import accr_nutritional_needs
from . import accr_student_food_intolerance
from . import accr_student_food_preferences
from . import accr_student_nutrition_details
from . import accr_meal_type
from . import accr_meal_timing
from . import accr_meal_timetable
from . import accr_medical_contraindication